### PR TITLE
Prefer epoll reactor for the log writer.

### PR DESCRIPTION
**Pull request by rmax**
This fixes an issue in restricted environments like AWS Lambda.

### CODE REVIEW

**Comment by itamarst** [comment]
Hi,

Sorry for the late reply, and thanks for the PR, will try to take a look at it soon.

Could you explain a bit more the issue with AWS Lambda?

**Comment by rmax** [comment]
Hi @itamarst 

Below is the exception we got when running a twisted function using crochet in AWS Lambda. 

```
START RequestId: 81b15494-557b-11e7-81e1-b51b4d1843be Version: $LATEST
2017-06-20 02:44:23.278 (-03:00)    81b15494-557b-11e7-81e1-b51b4d1843be    [CRITICAL]    Unhandled Error
Traceback (most recent call last):
  File "/var/lang/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/var/lang/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/tmp/tmpuvobj0o3/crochet/_eventloop.py", line 289, in _reader
    self._logWritingReactor.run(installSignalHandlers=False)
  File "/tmp/tmpuvobj0o3/twisted/internet/base.py", line 1243, in run
    self.mainLoop()
--- <exception caught here> ---
  File "/tmp/tmpuvobj0o3/twisted/internet/base.py", line 1255, in mainLoop
    self.doIteration(t)
  File "/tmp/tmpuvobj0o3/twisted/internet/pollreactor.py", line 155, in doPoll
    l = self._poller.poll(timeout)
builtins.PermissionError: [Errno 1] Operation not permitted
```

The AWS Lambda environment has some constraints regarding number of file descriptors and such: https://docs.aws.amazon.com/lambda/latest/dg/limits.html

However, AWS support was not able to pin point to me what was the particular reason that caused the poll reactor to fail with the `PermissionError` when there was no a large amount of opened file descriptors.

We deployed the fix in this PR and it's working as expected.

**Comment by itamarst** [comment]
I will try to get this fixed and released next week. That is a strange error, yes, will investigate further.

**Comment by itamarst** [comment]
I tried to figure out why this might be happening, and failed. But this patch seems perfectly reasonable on its own, and you've reported an improvement, so will just merge it as is.

Thanks!

**Comment by rmax** [comment]
Great! We will look forward for the pypi release.

**Comment by itamarst** [comment]
Just released 1.8.0.

**Pull request merged**
